export const specialities = [
  {id: 0, name: 'Dermatologia'},
  {id: 1, name: 'Cardiologia'},
  {id: 2, name: 'Neurologia'},
  {id: 3, name: 'Reumatologia'},
  {id: 4, name: 'Cirurgia torácica'},
  {id: 5, name: 'Urologia'},
  {id: 6, name: 'Gastroenterologia'},
  {id: 7, name: 'Hepatologia'},
  {id: 8, name: 'Alergia'},
  {id: 9, name: 'Nutrição obesidade'},
  {id: 10, name: 'Cirurgia vascular'},
  {id: 11, name: 'Cirurgia do aparelho digestivo'},
  {id: 12, name: 'Endocrinologia'},
  {id: 13, name: 'Cirurgia bariátrica'},
  {id: 14, name: 'Cirurgia oncológica'},
  {id: 15, name: 'Transplante hepático'},
  {id: 16, name: 'Teste alérgico'},
  {id: 17, name: 'Eletroencefalograma'},
  {id: 18, name: 'Fototerapia'},
  {id: 19, name: 'Consulta de enfermagem'},
  {id: 20, name: 'Nutrição'},
  {id: 21, name: 'Endocrinologia'},
  {id: 22, name: 'Bucomaxilo'},
  {id: 23, name: 'Psiquiatria'},
  {id: 24, name: 'Pneumologia'},
  {id: 25, name: 'Cardiologia'},
  {id: 26, name: 'Reumatologia'},
  {id: 27, name: 'Homeopatia'},
  {id: 28, name: 'Neurologia'},
  {id: 29, name: 'Clínica médica'},
  {id: 30, name: 'Consulta de enfermagem'},
  {id: 31, name: 'Ortopedia'},
  {id: 32, name: 'Neurologia'},
  {id: 33, name: 'Endocrinologia'},
  {id: 34, name: 'Psicologia'},
  {id: 35, name: 'Hematologia'},
  {id: 36, name: 'Psicologia/Obstetrícia'},
  {id: 37, name: 'Fisioterapia/Mastologia'},
  {id: 38, name: 'Ginecologia geral'},
  {id: 39, name: 'Ginecologia cirúrgica'},
  {id: 40, name: 'Uroginecologia'},
  {id: 41, name: 'Mastologia'},
  {id: 42, name: 'Pré-natal de alto risco'},
  {id: 43, name: 'Serviço Social/Bariátrica'},
  {id: 44, name: 'Consulta de enfermagem'},
  {id: 45, name: 'Endocrinologia - Pediatria'},
  {id: 46, name: 'Dermatologia - Pediatria'},
  {id: 47, name: 'Pediatria geral'},
  {id: 48, name: 'Nutrólogo - Pediatria'},
  {id: 49, name: 'Nutrição - Pediatria'},
  {id: 50, name: 'Gastroenterologia - Pediatria'},
  {id: 51, name: 'Homeopatia - Pediatria'},
  {id: 52, name: 'Oftalmologia'},
  {id: 53, name: 'Proctologia'},
  {id: 54, name: 'Urologia'},
  {id: 55, name: 'Psicologia'},
  {id: 56, name: 'Fisioterapia/Reumatologia'},
  {id: 57, name: 'Cirurgia de cabeça e pescoço'},
  {id: 58, name: 'Otorrinolaringologia'},
  {id: 59, name: 'Fonoaudiologia'},
  {id: 60, name: 'Acupuntura'},
  {id: 61, name: 'Cirurgia plástica'},
  {id: 62, name: 'Psiquiatria'},
  {id: 63, name: 'Hematologia'},
  {id: 64, name: 'Psquiatria infantil'},
];

export const hospitalizations = [
  {id: 0, name: 'Clínica Ginecológica'},
  {id: 1, name: 'Centro obstétrico (referência para alto risco)'},
  {id: 2, name: 'UTI Neonatal'},
  {id: 3, name: 'Alojamento Conjunto'},
  {id: 4, name: 'Oncohematologia'},
  {id: 5, name: 'Reumatologia'},
  {id: 6, name: 'Pneumologia'},
  {id: 7, name: 'Cardiologia'},
  {id: 8, name: 'Endocrinologia'},
  {id: 9, name: 'Gastroenterologia'},
  {id: 10, name: 'Clínica Médica'},
  {id: 11, name: 'Neurologia'},
  {id: 12, name: 'Unidade de tratamento dialítico (UTD)'},
  {id: 13, name: 'Unidade de terapia intensiva (UTI)'},
  {id: 14, name: 'Centro Cirúrgico'},
  {id: 15, name: 'Centro Endoscópico'},
  {id: 16, name: 'Pós-Transplante Hepático'},
  {id: 17, name: 'Cirurgia Geral'},
  {id: 18, name: 'Cirurgia Bariátrica'},
  {id: 19, name: 'Cabeça e pescoço'},
  {id: 20, name: 'Cirurgia torácica'},
  {id: 21, name: 'Otorrinolaringologia'},
  {id: 22, name: 'Bucomaxilo'},
  {id: 23, name: 'Cirurgia Vascular'},
  {id: 24, name: 'Cirurgia Plástica'},
  {id: 25, name: 'Urologia'},
  {id: 26, name: 'Proctologia'},
];
