"""Torna campo name de MedicalBedType nao unico

Revision ID: 04b6202dca0c
Revises: e4d92d9da534
Create Date: 2023-02-16 14:58:36.699443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '04b6202dca0c'
down_revision = 'e4d92d9da534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_bed_type_name', table_name='medical_bed_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_medical_bed_type_name', 'medical_bed_type', ['name'], unique=False)
    # ### end Alembic commands ###
