"""Adiciona campos em Patient

Revision ID: 0a5f183a886e
Revises: 304be4bff981
Create Date: 2023-02-11 21:35:44.039922

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '0a5f183a886e'
down_revision = '304be4bff981'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('email_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('CNS', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('CPF', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('RG', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('ethnic_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('is_deceased', sa.Boolean(), nullable=False))
    op.add_column('patient', sa.Column('is_deprived_of_liberty', sa.Boolean(), nullable=True))
    op.add_column('patient', sa.Column('has_disability', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'patient', ['CNS'])
    op.create_unique_constraint(None, 'patient', ['CPF'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='unique')
    op.drop_constraint(None, 'patient', type_='unique')
    op.drop_column('patient', 'has_disability')
    op.drop_column('patient', 'is_deprived_of_liberty')
    op.drop_column('patient', 'is_deceased')
    op.drop_column('patient', 'phone_number')
    op.drop_column('patient', 'ethnic_group')
    op.drop_column('patient', 'father_name')
    op.drop_column('patient', 'mother_name')
    op.drop_column('patient', 'RG')
    op.drop_column('patient', 'CPF')
    op.drop_column('patient', 'CNS')
    op.drop_column('patient', 'email_address')
    # ### end Alembic commands ###
