"""Make some patient_transference attributes nullables

Revision ID: 304be4bff981
Revises: d590c057c9de
Create Date: 2023-02-08 16:19:17.247250

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '304be4bff981'
down_revision = 'd590c057c9de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_transference', 'in_transit_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('patient_transference', 'completed_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_transference', 'completed_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('patient_transference', 'in_transit_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
