"""Torna campo em Hospital nullable

Revision ID: 352db8ece730
Revises: a8327ad6dc84
Create Date: 2023-02-14 17:38:41.201961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '352db8ece730'
down_revision = 'a8327ad6dc84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'phone_number_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospital', 'phone_number_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
