"""Adiciona restricao de unicidade em MedicalBed

Revision ID: 46d87b732395
Revises: 04b6202dca0c
Create Date: 2023-02-18 20:32:36.441093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '46d87b732395'
down_revision = '04b6202dca0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'medical_bed', ['number', 'medical_bed_type_id', 'hospital_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_bed', type_='unique')
    # ### end Alembic commands ###
