"""Adiciona campos em Doctor

Revision ID: 7c60add3834a
Revises: 352db8ece730
Create Date: 2023-02-15 00:06:01.489983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '7c60add3834a'
down_revision = '352db8ece730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('CPF', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doctor', sa.Column('RG', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'doctor', ['CPF'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='unique')
    op.drop_column('doctor', 'RG')
    op.drop_column('doctor', 'CPF')
    # ### end Alembic commands ###
