"""Make name field of MedicalSpecialty unique

Revision ID: 8286dcd48906
Revises: a17f14265837
Create Date: 2023-02-05 14:27:19.966573

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = '8286dcd48906'
down_revision = 'a17f14265837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_medical_specialty_name'), 'medical_specialty', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_specialty_name'), table_name='medical_specialty')
    # ### end Alembic commands ###
