"""Torna id de MedicalBedType nao incremental

Revision ID: 89ce8502827a
Revises: ddf419708298
Create Date: 2023-02-15 15:50:48.980831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = "89ce8502827a"
down_revision = "ddf419708298"
branch_labels = None
depends_on = None


# Thanks ChatGPT for the help with this task :c

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # Remove the default value and ownership of the id column
    op.execute("ALTER TABLE medical_bed_type ALTER COLUMN id DROP DEFAULT")

    # op.drop_index("ix_medical_bed_type_name", "medical_bed_type")

    op.execute("DROP SEQUENCE medical_bed_type_id_seq")

    # Change the type of the id column to an appropriate non-serial type
    # op.alter_column('medical_bed_type', 'id', type_=sa.Integer())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.execute("CREATE SEQUENCE medical_bed_type_id_seq")

    op.execute("ALTER TABLE medical_bed_type ALTER COLUMN id SET DEFAULT nextval('medical_bed_type_id_seq')")

    op.execute("ALTER SEQUENCE medical_bed_type_id_seq OWNED BY medical_bed_type.id")
