"""Adiciona campos em Patient

Revision ID: a8327ad6dc84
Revises: f205ee33275b
Create Date: 2023-02-14 15:46:42.469996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = 'a8327ad6dc84'
down_revision = 'f205ee33275b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('weight_in_kg', sa.Integer(), nullable=True))
    op.add_column('patient', sa.Column('height_in_cm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'height_in_cm')
    op.drop_column('patient', 'weight_in_kg')
    # ### end Alembic commands ###
