"""Add many to many relationship between doctor and hospital

Revision ID: cf238366b9d7
Revises: 8286dcd48906
Create Date: 2023-02-05 18:30:51.715232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = 'cf238366b9d7'
down_revision = '8286dcd48906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_hospital_link',
    sa.Column('doctor', sa.Integer(), nullable=False),
    sa.Column('hospital', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['hospital'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('doctor', 'hospital')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_hospital_link')
    # ### end Alembic commands ###
