"""Torna CPF e RG not nullable em Doctor

Revision ID: ddf419708298
Revises: 7c60add3834a
Create Date: 2023-02-15 00:07:45.806752

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = 'ddf419708298'
down_revision = '7c60add3834a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'CPF',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctor', 'RG',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'RG',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('doctor', 'CPF',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
