"""Adiciona patient_clinical_condition

Revision ID: f205ee33275b
Revises: 1e1f790d335c
Create Date: 2023-02-13 21:25:18.702303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add support for SQLModel


# revision identifiers, used by Alembic.
revision = 'f205ee33275b'
down_revision = '1e1f790d335c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_clinical_condition',
    sa.Column('heart_rate_in_beats_per_minute', sa.Integer(), nullable=False),
    sa.Column('respiratory_rate_in_breaths_per_minute', sa.Integer(), nullable=False),
    sa.Column('glascow_coma_scale', sa.Integer(), nullable=False),
    sa.Column('clinical_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('physical_exams', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subsidiary_exams', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conduct_taken', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transference_request_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transference_request_id'], ['transference_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transference_request_id')
    )
    op.create_table('update_of_patient_clinical_condition',
    sa.Column('datetime_of_update', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_clinical_condition_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_clinical_condition_id'], ['patient_clinical_condition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_of_patient_clinical_condition')
    op.drop_table('patient_clinical_condition')
    # ### end Alembic commands ###
